commit

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -2,15 +2,25 @@
 #
 # Transfer a file from client to server
 
-if (( $# < 3 ))
-then
-  printf 'Usage: %s PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY\n' "${0##*/}"
-  exit 1
+# check if all parameters are provided
+if [ $# -lt 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
 fi
 
-if (( $# < 4 ))
-then
-  scp -o 'StrictHostKeyChecking No' -- "$1" "$3@$2:"
+# assign parameter values to variables
+FILE=$1
+IP=$2
+USERNAME=$3
+SSH_KEY=$4
+
+# transfer the file using scp
+scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE" "$USERNAME@$IP:~"
+
+# check if the transfer was successful
+if [ $? -eq 0 ]; then
+    echo "File transfer successful!"
 else
-  scp -o 'StrictHostKeyChecking No' -i "$4" -- "$1" "$3@$2:"
+    echo "File transfer failed."
 fi
+
