commit

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,11 +1,25 @@
 #!/usr/bin/env bash
 # transfers a file from a client to a server
 
-if [[ $# -lt 3 ]]; then
-	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
-	exit
-elif [[ $# -eq 3 ]]; then
-	scp -o StrictHostKeyChecking=no $1 $3@$2:~/
-	exit
+# check if all parameters are provided
+if [ $# -lt 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
 fi
-scp -i $4 -o StrictHostKeyChecking=no $1 $3@$2:~/ 
+
+# assign parameter values to variables
+FILE=$1
+IP=$2
+USERNAME=$3
+SSH_KEY=$4
+
+# transfer the file using scp
+scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE" "$USERNAME@$IP:~"
+
+# check if the transfer was successful
+if [ $? -eq 0 ]; then
+    echo "File transfer successful!"
+else
+    echo "File transfer failed."
+fi
+
